### ISSUE TITLE
Errors trying to install and run example using Windows

### ISSUE THREAD

**Issue by markhayton** [dhigginbotham/restify-nedb#4]
C:\nodejs\node_modules\restify>npm install restify-nedb --save

npm WARN unmet dependency C:\nodejs\node_modules\npm\node_modules\npm-registry-c
lient\node_modules\couch-login requires request@'~2.9.202' but will load
npm WARN unmet dependency C:\nodejs\node_modules\npm\node_modules\request,
npm WARN unmet dependency which is version 2.42.0
restify-nedb@0.1.0 ..\restify-nedb
├── underscore@1.5.2
└── nedb@0.8.13 (async@0.2.9, mkdirp@0.3.5, binary-search-tree@0.2.3, underscore
@1.4.4)

Trying to run node example.js

C:\nodejs\node_modules\restify>node example.js
C:\nodejs\node_modules\restify\example.js:29
cfg.makeDataStore();
    ^
TypeError: Object [object Object] has no method 'makeDataStore'
    at Object.<anonymous> (C:\nodejs\node_modules\restify\example.js:29:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by royshum93** [comment]
I have encountered the same problem and I found that it is a typo in the script from the npm repo.

node_modules\restify-nedb\lib\config.js: 42

<pre>config.prototype.makeDateStore = function(fn) {</pre>

The method name is typed as "makeDateStore"  instead of "makeDataStore".
However, there is no such problem if you just git clone this repo from github.

**Comment by dhigginbotham** [comment]
@royshum93 @markhayton, wow, im sorry for not responding sooner -- I can fix this and hopefully clear up any problems in the future.

**Comment by dhigginbotham** [comment]
I've published that change to npm, `0.1.2`
