### ISSUE TITLE
Disable version option

### ISSUE THREAD

**Issue by royshum93** [dhigginbotham/restify-nedb#5]
Just saw the code about disabling version option, it should be able to turn version option off by setting <i>version = false</i>

However, the code seems not functioning in:
https://github.com/dhigginbotham/restify-nedb/blob/master/lib/mount.js#L22

The condition will always be fulfilled, and <i>this.version</i> in the resulting uri regardless of its value:
<pre>uri = util.format((this.version != null) || this.version !== false ? this.prefix + this.version : this.prefix);</pre>

Should it be something like this?
<pre>uri = util.format((this.version != null) && this.version !== false ? this.prefix + this.version : this.prefix);</pre>

**Comment by dhigginbotham** [comment]
oops, I would agree, if you want to submit a PR in coffee I can recompile if you cannot :+1:

**Comment by dhigginbotham** [comment]
@royshum93 I got it, updated the small amount of tests around this app to reflect the change to verify.
