### ISSUE TITLE
404 no matter what when using restify-nedb

### ISSUE THREAD

**Issue by dukedougal** [dhigginbotham/restify-nedb#6]
The source of my test app is here:  https://gist.github.com/dukedougal/9edb1e4fd525271c57c0

Here is the output of trying to use the restify-nedb API:

ubuntu@ugbuildserver:~$ curl -H "Content-Type: application/json" -X POST -d '{"username":"xyz","password":"xyz"}' http://localhost:1337/kernel
Cannot POST /kernel
ubuntu@ugbuildserver:~$ curl -H "Content-Type: application/json" -X POST -d '{"username":"xyz","password":"xyz"}' http://localhost:1337
Cannot POST /
ubuntu@ugbuildserver:~$ curl  -X POST -d '{"username":"xyz","password":"xyz"}' http://localhost:1337/kernel
Cannot POST /kernel
ubuntu@ugbuildserver:~$ curl  -X POST -d '{"username":"xyz","password":"xyz"}' http://localhost:1337/kernel
Cannot POST /kernel
ubuntu@ugbuildserver:~$ curl -H "Content-Type: application/json" -X POST -d '{"username":"xyz","password":"xyz"}' http://localhost:1337
Cannot POST /
ubuntu@ugbuildserver:~$ curl --verbose http://localhost:1337
* Rebuilt URL to: http://localhost:1337/
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 1337 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: localhost:1337
> Accept: */*
>
< HTTP/1.1 404 Not Found
< X-Powered-By: Express
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 13
< Vary: Accept-Encoding
< Date: Sun, 08 Nov 2015 02:38:35 GMT
< Connection: keep-alive
<
Cannot GET /
* Connection #0 to host localhost left intact
ubuntu@ugbuildserver:~$

**Comment by dukedougal** [comment]
In the end this was caused by a default value for "version" of "v1" being used.

I'd suggest the default for this be empty, especially as your documentation recommends against it anyway.....

**Comment by dhigginbotham** [comment]
@dukedougal I just fixed this for you, published up a new version to npm, sorry!
