### ISSUE TITLE
Remove usages of deprecated `req.param()`

### ISSUE THREAD

**Issue by dukedougal** [dhigginbotham/restify-nedb#7]
I am getting the following errors:

express deprecated req.param(name): Use req.params, req.body, or req.query instead node_modules/restify-nedb/lib/crudify.js:14:14
express deprecated req.param(name): Use req.params, req.body, or req.query instead node_modules/restify-nedb/lib/crudify.js:18:17
express deprecated req.param(name): Use req.params, req.body, or req.query instead node_modules/restify-nedb/lib/crudify.js:19:16
express deprecated req.param(name): Use req.params, req.body, or req.query instead node_modules/restify-nedb/lib/crudify.js:20:16

**Comment by dhigginbotham** [comment]
@dukedougal I fixed this issue as well!
